name: open_files_plugin
description: A Flutter plugin to count the number of open files on iOS.
version: 0.0.3
homepage: https://example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftOpenFilesPlugin
        swiftVersion: 5.0
